### ISSUE TITLE
Doubt regarding the installation.

### ISSUE THREAD

**Issue by PerzeusParker** [analytics-club-iitm/Daily-Sessions#1] opened 2020-03-24 15:33 UTC
Can i continue the setup in Kali Linux or is it necessary to get UBUNTU. I don't want to use anaconda on windows.

**Comment by MukundVarmaT** [comment] 2020-03-24 15:45
Sure why not. Although I am not exactly sure whether the script we have posted will work there. If you give me some time I will set up a VM and test it out for you.

**Comment by MukundVarmaT** [comment] 2020-03-24 19:24
Hey thanks for bringing it up. I tried running it on a VM.

**Just make the following changes!**

- Run these lines before running the script looks like kali-Linux doesn't come with snap installed.
```
sudo apt install snapd
sudo systemctl start snapd
sudo systemctl enable snapd
systemctl start apparmor
systemctl enable apparmor
echo "export PATH=$PATH:/snap/bin" >> ~/.bashrc
source ~/.bashrc
```

- Also in line number **100** - 
```execute sudo apt-get install run-one xbindkeys xbindkeys-config wmctrl xdotool -y```

remove the ```run-one``` from the above line.

------

Make sure you ```chmod +x ./setup_linux.sh```

Now you are good to go. You can run the script using ```./setup_linux.sh```.

Make sure to reboot the system once the script finishes. Once you do, you can see that your terminal is now coloured - with better tab suggestions, red highlighting when the command is incorrect and green when correct, etc. Also, you will be in your base environment in anaconda as well.

Do let me know if you face some other issues as well!

**Comment by MukundVarmaT** [comment] 2020-03-25 05:11
@PerzeusParker  Hey once the issue is solved please make sure to close the issue.

Thanks

**Comment by PerzeusParker** [comment] 2020-03-26 05:37
can i better use colab notebooks?
I think it can be a whole lot easier.
sure i will try the above mentioned process.

**Comment by MukundVarmaT** [comment] 2020-03-26 06:04
@PerzeusParker Definitely collab is easier to set up but if you only using it once cause each time you start a session you need to install everything again. 
I suggest doing this for sure cause its only a one time job and will make your life a lot easier.

**Closed as completed** 2020-04-01 03:07 UTC
